[package]
name = "logfmt"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
description = "tracing_subscriber layer for writing out logfmt formatted events"
edition = "2021"

[dependencies] # In alphabetical order
observability_deps = { path = "../observability_deps" }
tracing-subscriber = "0.3"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
once_cell = { version = "1.4.0", features = ["parking_lot"] }
parking_lot = "0.12"
regex = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
