[package]
name = "trogging"
version = "0.1.0"
authors = ["Marko Mikulicic <mkm@influxdata.com>"]
edition = "2018"
description = "IOx logging pipeline built upon tokio-tracing"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logfmt = { path = "../logfmt" }
observability_deps = { path = "../observability_deps" }
thiserror = "1.0.28"
tracing-log = "0.1"
tracing-subscriber = "0.2"
structopt = { version = "0.3.23", optional = true }

[dev-dependencies]
synchronized-writer = "1"
regex = "1"
