[package]
name = "trogging"
version = "0.1.0"
authors = ["Marko Mikulicic <mkm@influxdata.com>"]
edition = "2018"
description = "(TR)acing and l(OGGING) configuration"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logfmt = { path = "../logfmt" }
observability_deps = { path = "../observability_deps" }
opentelemetry-jaeger = { version = "0.14", features = ["tokio"], optional = true }
opentelemetry-otlp = { version = "0.8", optional = true }
thiserror = "1.0.23"
tracing-log = "0.1"
tracing-subscriber = "0.2"
tracing-opentelemetry = { version = "0.14", default-features = false }
structopt = { version = "0.3.21", optional = true }

[dev-dependencies]
synchronized-writer = "1"
regex = "1"

[features]
jaeger = ["opentelemetry-jaeger"]
otlp = ["opentelemetry-otlp"]
