[package]
name = "internal_types"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "InfluxDB IOx internal types, shared between IOx instances"
readme = "README.md"

[dependencies]
arrow = { version = "5.0", features = ["prettyprint"] }
hashbrown = "0.11"
indexmap = "1.6"
itertools = "0.10.1"
snafu = "0.6"
tokio = { version = "1.11", features = ["sync"] }

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
futures = "0.3"
tokio = { version = "1.11", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
