[package]
name = "internal_types"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "InfluxDB IOx internal types, shared between IOx instances"
readme = "README.md"

[dependencies]
parking_lot = "0.11"
snafu = "0.6"
time = { path = "../time" }
tokio = { version = "1.11", features = ["sync"] }

[dev-dependencies]
futures = "0.3"
tokio = { version = "1.11", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
