[package]
name = "iox_data_generator"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2021"
default-run = "iox_data_generator"

[dependencies]
chrono = { version = "0.4", default-features = false }
chrono-english = "0.1.4"
clap = "2.34.0"
futures = "0.3"
handlebars = "4.1.6"
humantime = "2.1.0"
data_types = { path = "../data_types" }
influxdb2_client = { path = "../influxdb2_client" }
influxdb_iox_client = { path = "../influxdb_iox_client" }
itertools = "0.10.0"
rand = { version = "0.8.3", features = ["small_rng"] }
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.72"
snafu = "0.7"
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
toml = "0.5.6"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "0.8.1", default_features = false }

[dev-dependencies]
criterion = "0.3.3"
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "point_generation"
harness = false
