[package]
name = "influxdb3_server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Core Crates
authz.workspace = true
data_types.workspace = true
datafusion_util.workspace = true
influxdb-line-protocol.workspace = true
iox_catalog.workspace = true
iox_http.workspace = true
iox_query.workspace = true
iox_query_params.workspace = true
iox_query_influxql.workspace = true
iox_system_tables.workspace = true
iox_time.workspace = true
metric.workspace = true
metric_exporters.workspace = true
observability_deps.workspace = true
schema.workspace = true
service_common.workspace = true
service_grpc_flight.workspace = true
trace.workspace = true
trace_exporters.workspace = true
trace_http.workspace = true
tracker.workspace = true

# Local Deps
influxdb3_cache = { path = "../influxdb3_cache" }
influxdb3_catalog = { path = "../influxdb3_catalog" }
influxdb3_config = { path = "../influxdb3_config" }
influxdb3_client = { path = "../influxdb3_client" }
influxdb3_id = { path = "../influxdb3_id" }
influxdb3_internal_api = { path = "../influxdb3_internal_api" }
influxdb3_process = { path = "../influxdb3_process", default-features = false }
influxdb3_processing_engine = { path = "../influxdb3_processing_engine" }
influxdb3_wal = { path = "../influxdb3_wal"}
influxdb3_write = { path = "../influxdb3_write" }
iox_query_influxql_rewrite = { path = "../iox_query_influxql_rewrite" }
influxdb3_sys_events = { path = "../influxdb3_sys_events" }
influxdb3_telemetry = { path = "../influxdb3_telemetry" }

# Enterprise Crates
influxdb3_enterprise_data_layout = { path = "../influxdb3_enterprise/data_layout" }
influxdb3_enterprise_compactor = { path = "../influxdb3_enterprise/compactor" }

# crates.io Dependencies
anyhow.workspace = true
arrow.workspace = true
arrow-array.workspace = true
arrow-csv.workspace = true
arrow-flight.workspace = true
arrow-json.workspace = true
arrow-schema.workspace = true
async-trait.workspace = true
base64.workspace = true
bytes.workspace = true
chrono.workspace = true
csv.workspace = true
datafusion.workspace = true
flate2.workspace = true
futures.workspace = true
hex.workspace = true
hyper.workspace = true
humantime.workspace = true
mime.workspace = true
object_store.workspace = true
parking_lot.workspace = true
pin-project-lite.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tower.workspace = true
unicode-segmentation.workspace = true

[dependencies.pyo3]
version = "0.23.3"
# this is necessary to automatically initialize the Python interpreter
features = ["auto-initialize"]
optional = true

[features]
system-py = ["pyo3"]

[dev-dependencies]
# Core Crates
parquet.workspace = true
parquet_file.workspace = true
test_helpers.workspace = true

# crates.io crates
http.workspace = true
hyper.workspace = true
test-log.workspace = true
urlencoding.workspace = true
pretty_assertions.workspace = true
