[package]
name = "ioxd_querier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
data_types = { path = "../data_types" }
generated_types = { path = "../generated_types" }
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
object_store = { path = "../object_store" }
querier = { path = "../querier" }
query = { path = "../query" }
service_grpc_flight = { path = "../service_grpc_flight" }
service_grpc_influxrpc = { path = "../service_grpc_influxrpc" }
iox_time = { path = "../iox_time" }
trace = { path = "../trace" }

# Crates.io dependencies, in alphabetical order
arrow-flight = "13"
async-trait = "0.1"
hyper = "0.14"
tokio = { version = "1.18", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tonic = "0.7"
workspace-hack = { path = "../workspace-hack"}


[dev-dependencies]
# Workspace dependencies, in alphabetical order
iox_tests = { path = "../iox_tests" }

# Crates.io dependencies, in alphabetical order
