[package]
name = "ioxd_querier"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
authz = { path = "../authz" }
clap_blocks = { path = "../clap_blocks" }
data_types = { path = "../data_types" }
datafusion_util = { path = "../datafusion_util"}
generated_types = { path = "../generated_types" }
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
object_store = { workspace = true }
querier = { path = "../querier" }
iox_query = { path = "../iox_query" }
service_grpc_catalog = { path = "../service_grpc_catalog"}
service_grpc_flight = { path = "../service_grpc_flight" }
service_grpc_influxrpc = { path = "../service_grpc_influxrpc" }
service_grpc_object_store = { path = "../service_grpc_object_store" }
service_grpc_schema = { path = "../service_grpc_schema" }
iox_time = { path = "../iox_time" }
trace = { path = "../trace" }

# Crates.io dependencies, in alphabetical order
arrow-flight = { workspace = true }
async-trait = "0.1"
hyper = "0.14"
thiserror = "1.0.44"
tokio = { version = "1.31", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tonic = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
tokio-util = "0.7.8"

[dev-dependencies]
# Workspace dependencies, in alphabetical order
iox_tests = { path = "../iox_tests" }

# Crates.io dependencies, in alphabetical order
