[package]
name = "delorean_storage_tool"
version = "0.1.0"
authors = ["Andrew Lamb <alamb@influxdata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# I get a build error when I use this one:
# failed to run custom build command for `arrow-flight v0.17.0`
#parquet = "0.17.0"
# We may have to live on the edge and pull directly from the arrow repo.
# good/bad an idea this is. If it is ok, we wil add directly as a dependency:
# https://doc.rust-lang.org/stable/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
#parquet = { path = "/Users/alamb/Software/arrow/rust/parquet", version = "0.18.0-SNAPSHOT" }
delorean_line_parser = { path = "../delorean_line_parser" }

clap = "2.33.1"
env_logger = "0.7.1"
log = "0.4.8"
snafu = "0.6.2"

[dev-dependencies]
predicates = "1.0.4"
assert_cmd = "1.0.0"

[[bin]]
# (D)elorian (S)torage Tool
name = "dstool"
path = "src/main.rs"
