[package]
name = "delorean_storage_tool"
version = "0.1.0"
authors = ["Andrew Lamb <alamb@influxdata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delorean_line_parser = { path = "../delorean_line_parser" }
delorean_ingest = { path = "../delorean_ingest" }
delorean_parquet = { path = "../delorean_parquet" }
delorean_table = { path = "../delorean_table" }
delorean_table_schema = { path = "../delorean_table_schema" }
delorean = { path = ".." }
libflate = "1.0.0"

clap = "2.33.1"
env_logger = "0.7.1"
log = "0.4.8"
snafu = "0.6.2"

[dev-dependencies]
predicates = "1.0.4"
assert_cmd = "1.0.0"
delorean_test_helpers = { path = "../delorean_test_helpers" }

[[bin]]
# (D)elorian (S)torage Tool
name = "dstool"
path = "src/main.rs"
