[package]
name = "import_export"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes = "1.5"
data_types = { path = "../data_types" }
futures-util = { version = "0.3" }
generated_types = { path = "../generated_types" }
influxdb_iox_client = { path = "../influxdb_iox_client", features = ["flight", "format"] }
iox_catalog = { path = "../iox_catalog"  }
parquet_file = { path = "../parquet_file"  }
object_store = { workspace=true }
observability_deps = { path = "../observability_deps" }
schema = { path = "../schema" }
serde_json = "1.0.106"
thiserror = "1.0.48"
tokio = { version = "1.32" }
tokio-util = { version = "0.7.8" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
