[package]
name = "packers"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow = { version = "5.0", features = ["prettyprint"] }
influxdb_tsm = { path = "../influxdb_tsm" }
internal_types = { path = "../internal_types" }
snafu = "0.6.2"
observability_deps = { path = "../observability_deps" }
parquet = "5.5"

[dev-dependencies] # In alphabetical order
criterion = "0.3.3"
rand = "0.8.3"
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "packers"
harness = false
