[package]
name = "packers"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"

[dependencies] # In alphabetical order
arrow = { version = "17.0.0", features = ["prettyprint"] }
influxdb_tsm = { path = "../influxdb_tsm" }
schema = { path = "../schema" }
snafu = "0.7"
parquet = "17.0.0"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
criterion = "0.3.6"
rand = "0.8.3"

[[bench]]
name = "packers"
harness = false
