language: go

go:
  - 1.4

install:
  - go get -d -v ./... && go build -v ./...
  - go get -u golang.org/x/tools/cmd/vet;

script: go test -v . ./messaging ./influxql; go vet ./...

notifications:
  email:
    on_success: never
    on_failure: change
