[[constraint]]
  name = "collectd.org"
  version = "0.3.0"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  branch = "master"

[[constraint]]
  name = "github.com/influxdata/roaring"
  branch = "master"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/cespare/xxhash"
  version = "1.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/snappy"
  revision = "d9eb7a3d35ec988b8585d4a0068e462c27d28380"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  branch = "master"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  branch = "master"

[[constraint]]
  name = "github.com/paulbellamy/ratecounter"
  version = "0.2.0"

[[constraint]]
  name = "github.com/retailnext/hllpp"
  branch = "master"

[[constraint]]
  name = "github.com/tinylib/msgp"
  version = "1.0.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "github.com/jsternberg/zap-logfmt"
  version = "1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "661e31bf844dfca9aeba15f27ea8aa0d485ad212"

[[constraint]]
  name = "github.com/klauspost/pgzip"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/influxdata/flux"
