[package]
name = "router"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
bytes = "1.4"
client_util = { path = "../client_util" }
data_types = { path = "../data_types" }
dml = { path = "../dml" }
flate2 = "1.0"
futures = "0.3.26"
generated_types = { path = "../generated_types" }
hashbrown = { workspace = true }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }
object_store = "0.5.4"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
predicate = { path = "../predicate" }
schema = { version = "0.1.0", path = "../schema" }
serde = "1.0"
serde_json = "1.0.93"
serde_urlencoded = "0.7"
service_grpc_catalog = { path = "../service_grpc_catalog"}
service_grpc_namespace = { path = "../service_grpc_namespace"}
service_grpc_schema = { path = "../service_grpc_schema" }
service_grpc_object_store = { path = "../service_grpc_object_store" }
sharder = { path = "../sharder" }
snafu = "0.7"
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = "0.8"
trace = { path = "../trace/" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
write_buffer = { path = "../write_buffer" }
write_summary = { path = "../write_summary" }
tower = { version = "0.4.13", features = ["balance"] }
crossbeam-utils = "0.8.15"

[dev-dependencies]
assert_matches = "1.5"
criterion = { version = "0.4", default-features = false, features = ["async_tokio", "rayon"]}
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
iox_tests = { path = "../iox_tests" }
once_cell = "1"
paste = "1.0.11"
pretty_assertions = "1.3.0"
rand = "0.8.3"
schema = { path = "../schema" }
test_helpers = { version = "0.1.0", path = "../test_helpers", features = ["future_timeout"] }
tokio-stream = { version = "0.1.12", default_features = false, features = [] }

[lib]
# Allow --save-baseline to work
# https://github.com/bheisler/criterion.rs/issues/275
bench = false

[[bench]]
name = "schema_validator"
harness = false

[[bench]]
name = "e2e"
harness = false
