[package]
name = "router"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
authz = { path = "../authz", features = ["http"] }
bytes = "1.4"
crossbeam-utils = "0.8.16"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
flate2 = "1.0"
futures = "0.3.28"
generated_types = { path = "../generated_types" }
gossip_schema = { version = "0.1.0", path = "../gossip_schema" }
hashbrown = { workspace = true }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
iox_time = { path = "../iox_time" }
merkle-search-tree = { version = "0.6.0", features = ["tracing"] }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }
object_store = { workspace = true }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
serde = "1.0"
serde_urlencoded = "0.7"
service_grpc_catalog = { path = "../service_grpc_catalog" }
service_grpc_namespace = { path = "../service_grpc_namespace" }
service_grpc_object_store = { path = "../service_grpc_object_store" }
service_grpc_schema = { path = "../service_grpc_schema" }
service_grpc_table = { path = "../service_grpc_table" }
sharder = { path = "../sharder" }
smallvec = "1.11.0"
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tonic = { workspace = true }
trace = { path = "../trace/" }
trace_http = { path = "../trace_http" }

workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1.5"
base64 = "0.21.3"
chrono = { version = "0.4.28", default-features = false }
criterion = { version = "0.5", default-features = false, features = [
    "async_tokio",
    "rayon",
] }
influxdb-line-protocol = { path = "../influxdb_line_protocol" }
iox_tests = { path = "../iox_tests" }
once_cell = "1"
paste = "1.0.14"
pretty_assertions = "1.4.0"
proptest = { version = "1.2.0", default-features = false }
rand = "0.8.3"
schema = { version = "0.1.0", path = "../schema" }
test_helpers = { version = "0.1.0", path = "../test_helpers", features = [
    "future_timeout",
] }
tokio = { version = "1", features = ["test-util"] }
tokio-stream = { version = "0.1.13", default_features = false, features = [] }

[lib]
# Allow --save-baseline to work
# https://github.com/bheisler/criterion.rs/issues/275
bench = false

[[bench]]
name = "schema_validator"
harness = false

[[bench]]
name = "partitioner"
harness = false

[[bench]]
name = "namespace_schema_cache"
harness = false
