[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
cache_loader_async = { version = "0.1.2", features = ["ttl-cache"] }
data_types = { path = "../data_types" }
dml = { path = "../dml" }
hashbrown = "0.11"
influxdb_iox_client = { path = "../influxdb_iox_client" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
observability_deps = { path = "../observability_deps" }
trace = { path = "../trace" }
parking_lot = "0.11.2"
snafu = "0.7"
time = { path = "../time" }
write_buffer = { path = "../write_buffer" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
mutable_batch_lp = { path = "../mutable_batch_lp" }
regex = "1"
tokio = { version = "1.13", features = ["macros", "parking_lot"] }

[features]
kafka = ["write_buffer/kafka"]
