[package]
name = "ingester2"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow-flight = { workspace = true }
arrow_util = { version = "0.1.0", path = "../arrow_util" }
async-channel = "1.8.0"
async-trait = "0.1.64"
backoff = { version = "0.1.0", path = "../backoff" }
bytes = "1.4.0"
crossbeam-utils = "0.8.14"
data_types = { version = "0.1.0", path = "../data_types" }
datafusion.workspace = true
datafusion_util = { path = "../datafusion_util" }
dml = { version = "0.1.0", path = "../dml" }
flatbuffers = "22"
futures = "0.3.26"
generated_types = { version = "0.1.0", path = "../generated_types" }
hashbrown.workspace = true
iox_catalog = { version = "0.1.0", path = "../iox_catalog" }
iox_query = { version = "0.1.0", path = "../iox_query" }
iox_time = { path = "../iox_time" }
metric = { version = "0.1.0", path = "../metric" }
mutable_batch = { version = "0.1.0", path = "../mutable_batch" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }
object_store = "0.5.2"
observability_deps = { version = "0.1.0", path = "../observability_deps" }
once_cell = "1.17"
parking_lot = "0.12.1"
parquet_file = { version = "0.1.0", path = "../parquet_file" }
pin-project = "1.0.12"
predicate = { version = "0.1.0", path = "../predicate" }
prost = { version = "0.11.6", default-features = false, features = ["std"] }
rand = "0.8.5"
schema = { version = "0.1.0", path = "../schema" }
service_grpc_catalog = { version = "0.1.0", path = "../service_grpc_catalog" }
sharder = { version = "0.1.0", path = "../sharder" }
thiserror = "1.0.38"
test_helpers = { path = "../test_helpers", features = ["future_timeout"], optional = true }
tokio = { version = "1.25", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tonic = "0.8.3"
trace = { version = "0.1.0", path = "../trace" }
uuid = "1.3.0"
wal = { version = "0.1.0", path = "../wal" }
workspace-hack = { path = "../workspace-hack"}
tokio-util = "0.7.4"

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.4", default-features = false, features = ["async_tokio"]}
datafusion_util = { path = "../datafusion_util" }
lazy_static = "1.4.0"
mutable_batch_lp = { path = "../mutable_batch_lp" }
paste = "1.0.11"
tempfile = "3.3.0"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }

[features]
benches = ["test_helpers"] # Export some internal types for benchmark purposes only.

[lib]
bench = false

[[bench]]
name = "wal"
harness = false
 # Require some internal types be made visible for benchmark code.
required-features = ["benches"]
