[package]
name = "iox_query_params"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
datafusion = { workspace = true }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"

