[package]
name = "sharder"
version = "0.1.0"
edition = "2021"

[dependencies]
data_types = { path = "../data_types" }
mutable_batch = { path = "../mutable_batch" }
parking_lot = "0.12"
siphasher = "0.3"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
criterion = { version = "0.3.6", features = ["async_tokio", "html_reports"] }
hashbrown = "0.12"
mutable_batch_lp = { path = "../mutable_batch_lp" }
rand = "0.8.3"
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "sharder"
harness = false

[lib]
# Allow --save-baseline to work
# https://github.com/bheisler/criterion.rs/issues/275
bench = false
