[package]
name = "test_helpers_end_to_end"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies] # In alphabetical order
arrow = { workspace = true }
arrow-flight = { workspace = true }
arrow_util = { path = "../arrow_util" }
assert_cmd = "2.0.13"
assert_matches = "1.5.0"
bytes = "1.5"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
futures = "0.3"
generated_types = { path = "../generated_types" }
http = "0.2.11"
hyper = "1.2"
influxdb_iox_client = { path = "../influxdb_iox_client", features = ["flight", "format"] }
ingester_query_grpc = { path = "../ingester_query_grpc" }
insta = { version = "1.34.0", features = ["yaml"] }
iox_catalog = { path = "../iox_catalog" }
iox_query_params = { path = "../iox_query_params" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
nix = { version = "0.27", default-features = false, features = ["signal"] }
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.19", features = ["parking_lot"] }
parking_lot = "0.12"
prost = { workspace = true }
rand = "0.8.3"
regex = "1.10"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-native-roots"] }
serde_json = "1.0.111"
snafu = "0.8"
sqlx = { version = "0.7.3", features = [ "runtime-tokio-rustls" , "postgres", "uuid" ] }
tempfile = "3.9.0"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
tokio = { version = "1.35", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = "0.7"
tonic = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
