[package]
name = "iox_query"
description = "IOx Query Interface and Executor"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# This crate is designed to be independent of the rest of the IOx
# server and specific storage systems such as Mutable Buffer and Read Buffer.
#
# The rationale for this is to:
#
# 1. Keep change/compile/link time down during development when working on just this crate
# 2. Allow for query logic testing without bringing in all the storage systems.

[dependencies] # In alphabetical order
arrow = { workspace = true, features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
async-trait = "0.1"
chrono = { version = "0.4", default-features = false }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
executor = { path = "../executor"}
futures = "0.3"
hashbrown = { workspace = true }
indexmap = { version = "2.0", features = ["std"] }
itertools = "0.11.0"
metric = { path = "../metric" }
object_store = { workspace = true }
observability_deps = { path = "../observability_deps" }
once_cell = "1"
parking_lot = "0.12"
parquet_file = { path = "../parquet_file" }
query_functions = { path = "../query_functions"}
schema = { path = "../schema" }
snafu = "0.7"
tokio = { version = "1.31", features = ["macros", "parking_lot"] }
tokio-stream = "0.1"
trace = { path = "../trace" }
predicate = { path = "../predicate" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
assert_matches = "1"
insta = { version = "1", features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
