[package]
name = "iox_query"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"
description = "IOx Query Interface and Executor"

# This crate is designed to be independent of the rest of the IOx
# server and specific storage systems such as Mutable Buffer and Read Buffer.
#
# The rationale for this is to:
#
# 1. Keep change/compile/link time down during development when working on just this crate
# 2. Allow for query logic testing without bringing in all the storage systems.

[dependencies] # In alphabetical order
arrow = { version = "21.0.0", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
async-trait = "0.1"
chrono = { version = "0.4", default-features = false }
croaring = "0.6"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
executor = { path = "../executor"}
futures = "0.3"
hashbrown = "0.12"
itertools = "0.10.2"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
query_functions = { path = "../query_functions"}
schema = { path = "../schema" }
snafu = "0.7"
tokio = { version = "1.20", features = ["macros", "parking_lot"] }
tokio-stream = "0.1"
trace = { path = "../trace" }
predicate = { path = "../predicate" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
