[package]
name = "service_grpc_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
tonic = "0.6"
workspace-hack = { path = "../workspace-hack"}
