[package]
name = "service_grpc_testing"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
tonic = "0.8"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
