[package]
name = "mutable_batch_entry"
version = "0.1.0"
edition = "2018"
description = "Conversion logic for entry flatbuffer <-> MutableBatch"

[dependencies]
entry = { path = "../entry" }
hashbrown = "0.11"
mutable_batch = { path = "../mutable_batch" }
schema = { path = "../schema" }
snafu = "0.6"

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
data_types = { path = "../data_types" }
flatbuffers = "2"
