[package]
name = "iox_tests"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2021"
description = "IOx test utils and tests"

[dependencies]
arrow = "20.0.0"
bytes = "1.2"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
iox_catalog = { path = "../iox_catalog" }
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
object_store = "0.4.0"
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.13.1", features = ["parking_lot"] }
parquet_file = { path = "../parquet_file" }
iox_query = { path = "../iox_query" }
schema = { path = "../schema" }
sharder = { path = "../sharder" }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}
futures = "0.3.23"
