[package]
name = "write_buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
data_types = { path = "../data_types" }
dotenv = "0.15.0"
futures = "0.3"
generated_types = { path = "../generated_types" }
http = "0.2"
httparse = "1.5"
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.2"
pin-project = "1.0"
prost = "0.8"
rdkafka = "0.27.0"
time = { path = "../time" }
tokio = { version = "1.13", features = ["macros", "fs"] }
trace = { path = "../trace" }
trace_http = { path = "../trace_http" }
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
tempfile = "3.1.0"

[package.metadata.cargo-udeps.ignore]
# used within the `maybe_skip_kafka_integration` macro and cannot be detected by a normal analysis pass
normal = ["dotenv"]
