[package]
name = "write_buffer"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
data_types = { path = "../data_types" }
entry = { path = "../entry" }
futures = "0.3"
parking_lot = "0.11.1"
rdkafka = "0.26.0"

[dev-dependencies]
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["macros", "fs"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
