[package]
name = "write_buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
dotenv = "0.15.0"
futures = "0.3"
generated_types = { path = "../generated_types", features = ["data_types_conversions"] }
http = "0.2"
httparse = "1.5"
metric = { path = "../metric" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.2"
pin-project = "1.0"
prost = "0.9"
rdkafka = { version = "0.28.0", optional = true }
time = { path = "../time" }
tokio = { version = "1.13", features = ["fs", "macros", "parking_lot", "rt", "sync", "time"] }
tokio-util = "0.6.9"
trace = { path = "../trace" }
trace_http = { path = "../trace_http" }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[features]
kafka = ["rdkafka"]

[dev-dependencies]
tempfile = "3.1.0"

[package.metadata.cargo-udeps.ignore]
# used within the `maybe_skip_kafka_integration` macro and cannot be detected by a normal analysis pass
normal = ["dotenv"]
