[package]
name = "ioxd_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
trace = { path = "../trace" }


# Crates.io dependencies, in alphabetical order
async-trait = "0.1"
clap = { version = "3", features = ["derive", "env"] }
hyper = "0.14"
snafu = "0.7"
tokio-util = { version = "0.7.1" }
workspace-hack = { path = "../workspace-hack"}
