[package]
name = "ioxd_test"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
trace = { path = "../trace" }

# Crates.io dependencies, in alphabetical order
async-trait = "0.1"
clap = { version = "4", features = ["derive", "env"] }
hyper = "0.14"
snafu = "0.8"
tokio-util = "0.7.10"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
