[package]
name = "influxrpc_parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sqlparser = {workspace = true}
snafu = "0.8.0"
generated_types = { path = "../generated_types" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
