[package]
name = "influxrpc_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlparser = "0.26.0"
snafu = "0.7.3"

generated_types = { path = "../generated_types" }
workspace-hack = { path = "../workspace-hack"}