[package]
name = "parquet_file"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
arrow = { workspace = true, features = ["prettyprint"] }
base64 = "0.21"
bytes = "1.4"
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
futures = "0.3"
generated_types = { path = "../generated_types" }
iox_time = { path = "../iox_time" }
object_store = { workspace = true }
observability_deps = { path = "../observability_deps" }
parquet = { workspace = true, features = ["experimental"]}
pbjson-types = "0.5"
prost = "0.11"
schema = { path = "../schema" }
snafu = "0.7"
thiserror = "1.0.44"
thrift = "0.17"
tokio = { version = "1.29", features = ["macros", "parking_lot", "rt", "rt-multi-thread", "sync"] }
uuid = { version = "1", features = ["v4"] }
zstd = "0.12"
workspace-hack = { version = "0.1", path = "../workspace-hack" }


[dev-dependencies] # In alphabetical order
rand = "0.8.3"
test_helpers = { version = "0.1.0", path = "../test_helpers" }