[package]
name = "parquet_file"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2021"

[dependencies] # In alphabetical order
arrow = { version = "7.0", features = ["prettyprint"] }
base64 = "0.13"
bytes = "1.0"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
futures = "0.3"
generated_types = { path = "../generated_types" }
iox_object_store = { path = "../iox_object_store" }
metric = { path = "../metric" }
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
parquet = "7.0"
parquet-format = "4.0"
parking_lot = "0.11.1"
pbjson-types = "0.2"
persistence_windows = { path = "../persistence_windows" }
predicate = { path = "../predicate" }
prost = "0.9"
snafu = "0.7"
schema = { path = "../schema" }
tempfile = "3.1.0"
thrift = "0.13"
time = { path = "../time" }
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt", "rt-multi-thread", "sync"] }
tokio-stream = "0.1"
uuid = { version = "0.8", features = ["v4"] }
zstd = "0.9"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
test_helpers = { path = "../test_helpers" }
