[package]
name = "parquet_file"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2021"

[dependencies] # In alphabetical order
arrow = { version = "19.0.0", features = ["prettyprint"] }
base64 = "0.13"
bytes = "1.2"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
futures = "0.3"
generated_types = { path = "../generated_types" }
iox_time = { path = "../iox_time" }
object_store = "0.3.0"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
parquet = {version = "19.0.0", features = ["experimental"]}
parquet-format = "4.0"
pbjson-types = "0.3"
predicate = { path = "../predicate" }
prost = "0.10"
schema = { path = "../schema" }
snafu = "0.7"
thrift = "0.13"
tokio = { version = "1.20", features = ["macros", "parking_lot", "rt", "rt-multi-thread", "sync"] }
uuid = { version = "1", features = ["v4"] }
zstd = "0.11"
workspace-hack = { path = "../workspace-hack"}
thiserror = "1.0.32"
