[package]
name = "test_helpers"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
dotenvy = "0.15.6"
parking_lot = "0.12"
tempfile = "3.4.0"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
observability_deps = { path = "../observability_deps" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
async-trait = { version = "0.1.64", optional = true }
tokio = { version = "1.25.0", optional = true, default_features = false, features = ["time"] }

[features]
default = []
future_timeout = ["async-trait", "tokio"]
