[package]
name = "mutable_buffer"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow = { version = "6.0", features = ["prettyprint"] }
data_types = { path = "../data_types" }
entry = { path = "../entry" }
schema = { path = "../schema" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.2"
snafu = "0.6.2"

[dev-dependencies] # In alphabetical order
tokio = { version = "1.11", features = ["macros"] }
arrow_util = { path = "../arrow_util" }
test_helpers = { path = "../test_helpers" }

[features]
default = []
# Disables snapshot caching
nocache = []
