[package]
name = "mutable_buffer"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"

# Note the long term goal is that this crate is standalone and not
# dependent on the IOx Query Engine (even though this is not the case
# now).
#
# The rationale for this is:
#
# 1. Keep the API clean (and concerns separated) and allow for potential future reuse outside of IOx
# 2. Keep change/compile/link time down during development when working on just this crate

[dependencies] # In alphabetical order
arrow_deps = { path = "../arrow_deps" }
async-trait = "0.1"
chrono = "0.4"
data_types = { path = "../data_types" }
flatbuffers = "0.6" # TODO: Update to 0.8
generated_types = { path = "../generated_types" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
snafu = "0.6.2"
string-interner = "0.12.2"
tokio = { version = "1.0", features = ["macros"] }
tracing = "0.1"

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
criterion = "0.3"
