[package]
name = "mutable_buffer"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"

[dependencies] # In alphabetical order
arrow = { version = "7.0", features = ["prettyprint"] }
data_types = { path = "../data_types" }
schema = { path = "../schema" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.2"
snafu = "0.7"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
arrow_util = { path = "../arrow_util" }
test_helpers = { path = "../test_helpers" }

[features]
default = []
# Disables snapshot caching
nocache = []
