[package]
name = "mutable_buffer"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"

# Note the long term goal is that this crate is standalone and not
# dependent on the IOx Query Engine (even though this is not the case
# now).
#
# The rationale for this is:
#
# 1. Keep the API clean (and concerns separated) and allow for potential future reuse outside of IOx
# 2. Keep change/compile/link time down during development when working on just this crate

[dependencies] # In alphabetical order
arrow = { path = "../arrow" }
ahash = "0.7.2"
async-trait = "0.1"
data_types = { path = "../data_types" }
# See docs/regenerating_flatbuffers.md about updating generated code when updating the
# version of the flatbuffers crate
flatbuffers = "0.8"
generated_types = { path = "../generated_types" }
hashbrown = "0.9.1"
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
internal_types = { path = "../internal_types" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.1"
snafu = "0.6.2"
tokio = { version = "1.0", features = ["macros"] }
tracker = { path = "../tracker" }

[dev-dependencies] # In alphabetical order
arrow_util = { path = "../arrow_util" }
test_helpers = { path = "../test_helpers" }
criterion = "0.3"
flate2 = "1.0.20"
rand = "0.8.3"

[features]
default = []
# Disables snapshot caching
nocache = []

[[bench]]
name = "snapshot"
harness = false

[[bench]]
name = "write"
harness = false
