[package]
name = "grpc-router-test-gen"
version = "0.1.0"
authors = ["Marko Mikulicic <mkm@influxdata.com>"]
edition = "2018"
description = "Protobuf used in test for the grpc-router crate; need to be in a separate create because of linter limitations"

[dependencies]
tonic = "0.5"
prost = "0.8"
prost-types = "0.8"

[build-dependencies]
tonic-build = "0.5"
prost-build = "0.8"
