[package]
name = "ingest"
version = "0.1.0"
authors = ["Andrew Lamb <alamb@influxdata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.2"
env_logger = "0.7.1"
tracing = "0.1"

influxdb_line_protocol = { path = "../influxdb_line_protocol" }
packers = { path = "../packers" }
data_types = { path = "../data_types" }
tsm = { path = "../tsm" }
arrow_deps = { path = "../arrow_deps" }

[dev-dependencies]
test_helpers ={ path = "../test_helpers" }
libflate = "1.0.0"
