[package]
name = "service_grpc_influxrpc"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
predicate = { path = "../predicate" }
iox_query = { path = "../iox_query" }
query_functions = { path = "../query_functions"}
schema = { path = "../schema" }
service_common = { path = "../service_common" }
trace = { path = "../trace"}
trace_http = { path = "../trace_http"}
tracker = { path = "../tracker" }

# Crates.io dependencies, in alphabetical order
arrow = { workspace = true, features = ["prettyprint"] }
async-trait = "0.1"
futures = "0.3"
pin-project = "1.0"
prost = "0.11"
regex = "1.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"
snafu = "0.7"
tokio = { version = "1.25", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.8"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
# Workspace dependencies, in alphabetical order
datafusion_util = { path = "../datafusion_util" }
influxdb_storage_client = { path = "../influxdb_storage_client" }
metric = { path = "../metric" }
panic_logging = { path = "../panic_logging" }
test_helpers = { path = "../test_helpers" }
trace_http = { path = "../trace_http" }
service_grpc_testing = { path = "../service_grpc_testing" }

# Crates.io dependencies, in alphabetical order
parking_lot = "0.12"
serde_urlencoded = "0.7.0"
