[package]
name = "service_grpc_influxrpc"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
predicate = { path = "../predicate" }
influxdb_storage_client = { path = "../influxdb_storage_client", optional = true }
iox_query = { path = "../iox_query" }
query_functions = { path = "../query_functions"}
service_common = { path = "../service_common" }
service_grpc_testing = { path = "../service_grpc_testing", optional = true }
tokio = { version = "1.31", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"], optional = true }
trace = { path = "../trace"}
trace_http = { path = "../trace_http"}
tracker = { path = "../tracker" }

# Crates.io dependencies, in alphabetical order
arrow = { workspace = true, features = ["prettyprint"] }
futures = "0.3"
pin-project = "1.1"
prost = "0.11"
regex = "1.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.104"
snafu = "0.7"
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
# Workspace dependencies, in alphabetical order
datafusion_util = { path = "../datafusion_util" }
influxdb_storage_client = { path = "../influxdb_storage_client" }
metric = { path = "../metric" }
panic_logging = { path = "../panic_logging" }
schema = { path = "../schema" }
service_grpc_testing = { path = "../service_grpc_testing" }
test_helpers = { path = "../test_helpers" }
trace_http = { path = "../trace_http" }

# Crates.io dependencies, in alphabetical order
parking_lot = "0.12"
tokio = { version = "1.31", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }

[features]
test-util = ["influxdb_storage_client", "service_grpc_testing", "tokio"]

[[test]]
name = "log_on_panic"
required-features = ["test-util"]
