[package]
name = "iox_query_influxql"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
chrono-tz = { version = "0.8" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
generated_types = { path = "../generated_types" }
influxdb_influxql_parser = { path = "../influxdb_influxql_parser" }
iox_query = { path = "../iox_query" }
itertools = "0.11.0"
observability_deps = { path = "../observability_deps" }
once_cell = "1"
predicate = { path = "../predicate" }
query_functions = { path = "../query_functions" }
regex = "1"
schema = { path = "../schema" }
serde_json = "1.0.104"
thiserror = "1.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
chrono = { version = "0.4", default-features = false }
test_helpers = { path = "../test_helpers" }
assert_matches = "1"
insta = { version = "1", features = ["yaml"] }
