[package]
name = "influxdb3_wal"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Core crates
data_types.workspace = true
iox_time.workspace = true
influxdb-line-protocol = { workspace = true }
observability_deps.workspace = true
schema.workspace =  true

# Local Crates
influxdb3_id = { path = "../influxdb3_id" }
influxdb3_shutdown = { path = "../influxdb3_shutdown" }

# crates.io dependencies
async-trait.workspace = true
bitcode.workspace = true
byteorder.workspace = true
bytes.workspace = true
crc32fast.workspace  = true
futures-util.workspace = true
hashbrown.workspace = true
indexmap.workspace = true
object_store.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_with.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true

[dev-dependencies]
test-log.workspace = true
