[package]
name = "iox_catalog_service"
version = "0.1.0"
edition = "2021"

[dependencies]
data_types = { path = "../data_types" }
generated_types = { path = "../generated_types" }
iox_catalog = { path = "../iox_catalog" }
observability_deps = { path = "../observability_deps" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = "0.7"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
metric = { path = "../metric" }
uuid = { version = "0.8", features = ["v4"] }
