[package]
name = "grpc-router"
version = "0.1.0"
authors = ["Marko Mikulicic <mkm@influxdata.com>"]
edition = "2021"

[dependencies]
bytes = "1.0"
cache_loader_async = {version  = "0.1.2", features = ["ttl-cache"] }
futures = "0.3"
observability_deps = { path = "../observability_deps" }
paste = "1.0.6"
prost = "0.9"
prost-types = "0.9"
thiserror = "1.0.30"
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.6.9" }
tonic = "0.6"
tonic-reflection = "0.3.0"

[build-dependencies]
paste = "1.0.6"
prost-build = "0.9"
tonic-build = "0.6"

[dev-dependencies]
grpc-router-test-gen = { path = "../grpc-router-test-gen" }
