# Welcome to the InfluxDB configuration file.

[meta]
  dir = "/var/opt/influxdb/meta"
  hostname = "localhost"
  bind-address = ":8088"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"

[data]
  dir = "/var/opt/influxdb/data"
  retention-auto-create = true
  retention-check-enabled = true
  retention-check-period = "10m0s"
  retention-create-period = "45m0s"

[cluster]
  shard-writer-timeout = "5s"

[retention]
  enabled = true
  check-interval = "10m0s"

[admin]
  enabled = true
  bind-address = ":8083"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false

[collectd]
  enabled = false
  bind-address = ""
  database = ""
  typesdb = ""

[opentsdb]
  enabled = false
  bind-address = ""
  database = ""
  retention-policy = ""

[udp]
  enabled = false
  bind-address = ""
  database = ""
  batch-size = 0
  batch-timeout = "0"

# Once every 24 hours InfluxDB will report anonymous data to m.influxdb.com
# The data includes randomly-generated ids, os, arch and version.
# We don't track ip addresses of servers reporting. This is only used
# to track the number of instances running and the versions, which
# is very helpful for us.
[monitoring]
  enabled = false
  write-interval = "1m0s"

[continuous_queries]
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"

[hinted-handoff]
  enabled = true
  dir = "/var/opt/influxdb/hh"
  max-size = 1073741824
  max-age = "168h0m0s"
  retry-rate-limit = 0
  retry-interval = "1s"
