[package]
name = "influxdb_iox_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["flight", "format"]
flight = ["arrow", "arrow-flight", "arrow_util"]
format = ["arrow", "arrow_util"]

[dependencies]
arrow = { workspace = true, optional = true }
arrow-flight = { workspace = true, optional = true, features=["flight-sql-experimental"] }
arrow_util = { path = "../arrow_util", optional = true }
bytes = "1.4"
client_util = { path = "../client_util" }
comfy-table = { version = "7.0", default-features = false}
futures-util = { version = "0.3" }
influxdb-line-protocol = { path = "../influxdb_line_protocol"}
generated_types = { path = "../generated_types" }
prost = "0.11"
rand = "0.8.3"
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls"] }
schema = { path = "../schema" }
serde_json = "1.0.104"
tokio = { version = "1.31", features = ["macros", "parking_lot", "rt-multi-thread"] }
tokio-stream = "0.1.13"
thiserror = "1.0.44"
tonic = { workspace = true }

[dev-dependencies]
insta = { version = "1" }
