[package]
name = "influxdb_iox_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["flight", "format"]
flight = ["arrow", "arrow-flight", "arrow_util", "futures-util"]
format = ["arrow", "arrow_util"]

[dependencies]
arrow = { workspace = true, optional = true }
arrow-flight = { workspace = true, optional = true, features=["flight-sql-experimental"] }
arrow_util = { path = "../arrow_util", optional = true }
bytes = "1.4"
client_util = { path = "../client_util" }
futures-util = { version = "0.3", optional = true }
influxdb_line_protocol = { path = "../influxdb_line_protocol"}
generated_types = { path = "../generated_types", default-features = false, features = ["data_types_conversions"] }
prost = "0.11"
rand = "0.8.3"
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls"] }
tokio = { version = "1.25", features = ["macros", "parking_lot", "rt-multi-thread"] }
tokio-stream = "0.1.12"
thiserror = "1.0.38"
tonic = { version = "0.8" }
trace_http = { path = "../trace_http" }
