[package]
name = "influxdb_iox_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["flight", "format"]
flight = ["arrow", "arrow-flight", "arrow_util"]
format = ["arrow", "arrow_util"]

[dependencies]
arrow = { workspace = true, optional = true }
arrow-flight = { workspace = true, optional = true }
arrow_util = { path = "../arrow_util", optional = true }
bytes = "1.5"
client_util = { path = "../client_util" }
comfy-table = { version = "7.1", default-features = false}
futures-util = { version = "0.3" }
influxdb-line-protocol = { path = "../influxdb_line_protocol"}
iox_query_params = { path = "../iox_query_params" }
generated_types = { path = "../generated_types" }
prost = { workspace = true }
rand = "0.8.3"
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls-native-roots"] }
schema = { path = "../schema" }
serde_json = "1.0.114"
tokio = { version = "1.35", features = ["macros", "parking_lot", "rt-multi-thread"] }
tokio-stream = "0.1.13"
thiserror = "1.0.56"
tonic = { workspace = true }

[dev-dependencies]
insta = { version = "1" }
