[package]
name = "influxdb_iox_client"
version = "0.1.0"
authors = ["Dom Dwyer <dom@itsallbroken.com>"]
edition = "2021"

[features]
flight = ["arrow", "arrow-flight", "arrow_util", "serde/derive", "serde_json", "futures-util"]
format = ["arrow", "arrow_util"]
write_lp = ["dml", "mutable_batch", "mutable_batch_lp", "mutable_batch_pb"]

[dependencies]
# Workspace dependencies, in alphabetical order
arrow_util = { path = "../arrow_util", optional = true }
client_util = { path = "../client_util" }
generated_types = { path = "../generated_types" }

# Crates.io dependencies, in alphabetical order
arrow = { version = "7.0", optional = true }
arrow-flight = { version = "7.0", optional = true }
bytes = "1.0"
futures-util = { version = "0.3", optional = true }
dml = { path = "../dml", optional = true }
mutable_batch = { path = "../mutable_batch", optional = true }
mutable_batch_lp = { path = "../mutable_batch_lp", optional = true }
mutable_batch_pb = { path = "../mutable_batch_pb", optional = true }
prost = "0.9"
rand = "0.8.3"
serde = "1.0.128"
serde_json = { version = "1.0.72", optional = true }
thiserror = "1.0.30"
tonic = { version = "0.6" }
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies] # In alphabetical order
serde_json = "1.0"
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread"] }
