[package]
name = "influxdb_iox_client"
version = "0.1.0"
authors = ["Dom Dwyer <dom@itsallbroken.com>"]
edition = "2018"

[features]
flight = ["arrow", "arrow-flight", "arrow_util", "serde/derive", "serde_json", "futures-util"]
format = ["arrow"]

[dependencies]
# Workspace dependencies, in alphabetical order
arrow_util = { path = "../arrow_util", optional = true }
client_util = { path = "../client_util" }
generated_types = { path = "../generated_types" }

# Crates.io dependencies, in alphabetical order
arrow = { version = "5.0", optional = true }
arrow-flight = { version = "5.0", optional = true }
futures-util = { version = "0.3.1", optional = true }
prost = "0.8"
rand = "0.8.3"
serde = "1.0.128"
serde_json = { version = "1.0.67", optional = true }
thiserror = "1.0.28"
tonic = { version = "0.5.0" }

[dev-dependencies] # In alphabetical order
serde_json = "1.0"
tokio = { version = "1.11", features = ["macros"] }
