[package]
name = "influxdb2_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies] # In alphabetical order
bytes = "1.5"
futures = { version = "0.3", default-features = false }
reqwest = { version = "0.11", default-features = false, features = ["stream", "json", "rustls-tls-native-roots"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.111"
snafu = "0.8"
url = "2.5.0"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies] # In alphabetical order
mockito = { version ="1.3", default-features = false }
once_cell = { version = "1.19", features = ["parking_lot"] }
parking_lot = "0.12"
tokio = { version = "1.35", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
test_helpers = { path = "../test_helpers" }
