[package]
name = "influxdb2_client"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2021"

[dependencies] # In alphabetical order
bytes = "1.0"
futures = { version = "0.3", default-features = false }
reqwest = { version = "0.11", default-features = false, features = ["stream", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
snafu = "0.7"
url = "2.1.1"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies] # In alphabetical order
mockito = "0.31"
once_cell = { version = "1.10.0", features = ["parking_lot"] }
parking_lot = "0.12"
tokio = { version = "1.17", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
test_helpers = { path = "../test_helpers" }
