[package]
name = "influxdb2_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
bytes = "1.4"
futures = { version = "0.3", default-features = false }
reqwest = { version = "0.11", default-features = false, features = ["stream", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
snafu = "0.7"
url = "2.4.1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies] # In alphabetical order
mockito = { version ="1.1", default-features = false }
once_cell = { version = "1.18", features = ["parking_lot"] }
parking_lot = "0.12"
tokio = { version = "1.32", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
test_helpers = { path = "../test_helpers" }
