[package]
name = "influxdb2_client"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
bytes = { version = "1.0", default-features = false }
futures = { version = "0.3", default-features = false }
reqwest = { version = "0.11", features = ["stream", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.67"
snafu = "0.6.6"
url = "2.1.1"

[dev-dependencies] # In alphabetical order
mockito = "0.30"
once_cell = { version = "1.4.0", features = ["parking_lot"] }
parking_lot = "0.11.2"
tokio = { version = "1.11", features = ["macros", "rt-multi-thread"] }
test_helpers = { path = "../test_helpers" }
