[package]
name = "mem_qe"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow = { version = "5.0", features = ["prettyprint"] }
chrono = "0.4"
croaring = "0.5"
crossbeam = "0.8"
env_logger = "0.8"
human_format = "1.0.3"
packers = { path = "../packers" }
snafu = "0.6.8"
observability_deps = { path = "../observability_deps" }
parquet = "5.0"

[dev-dependencies] # In alphabetical order
criterion = "0.3"
