[package]
name = "ioxd_ingester"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies, in alphabetical order
clap_blocks = { path = "../clap_blocks" }
data_types = { path = "../data_types" }
ingester = { path = "../ingester" }
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
object_store = "0.3.0"
iox_query = { path = "../iox_query" }
trace = { path = "../trace" }
write_buffer = { path = "../write_buffer" }

# Crates.io dependencies, in alphabetical order
async-trait = "0.1"
hyper = "0.14"
thiserror = "1.0.32"
workspace-hack = { path = "../workspace-hack"}
