[package]
name = "server"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow_deps = { path = "../arrow_deps" }
async-trait = "0.1"
bytes = "1.0"
chrono = "0.4"
crc32fast = "1.2.0"
data_types = { path = "../data_types" }
flatbuffers = "0.6" # TODO: Update to 0.8
futures = "0.3.7"
generated_types = { path = "../generated_types" }
hashbrown = "0.9.1"
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
mutable_buffer = { path = "../mutable_buffer" }
object_store = { path = "../object_store" }
parking_lot = "0.11.1"
pin-project = "1.0"
query = { path = "../query" }
read_buffer = { path = "../read_buffer" }
serde = "1.0"
serde_json = "1.0"
snafu = "0.6"
snap = "1.0.0"
tokio = { version = "1.0", features = ["macros", "time"] }
tokio-util = { version = "0.6.3" }
tracing = "0.1"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
