[package]
name = "server"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow = { version = "4.0", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
async-trait = "0.1"
bytes = { version = "1.0" }
chrono = "0.4"
cached = "0.23.0"
crc32fast = "1.2.0"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
entry = { path = "../entry" }
# See docs/regenerating_flatbuffers.md about updating generated code when updating the
# version of the flatbuffers crate
flatbuffers = "0.8"
futures = "0.3"
futures-util = { version = "0.3.1" }
generated_types = { path = "../generated_types" }
hashbrown = "0.11"
influxdb_iox_client = { path = "../influxdb_iox_client" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
internal_types = { path = "../internal_types" }
itertools = "0.10.1"
lifecycle = { path = "../lifecycle" }
metrics = { path = "../metrics" }
mutable_buffer = { path = "../mutable_buffer" }
num_cpus = "1.13.0"
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.1"
parquet_file = { path = "../parquet_file" }
query = { path = "../query" }
rand = "0.8.3"
rand_distr = "0.4.0"
read_buffer = { path = "../read_buffer" }
serde = "1.0"
serde_json = "1.0"
snafu = "0.6"
snap = "1.0.0"
tempfile = "3.1.0"
tikv-jemalloc-ctl = "0.4.0"
tokio = { version = "1.0", features = ["macros", "time"] }
tokio-util = { version = "0.6.3" }
tracker = { path = "../tracker" }
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies] # In alphabetical order
arrow_util = { path = "../arrow_util" }
datafusion = { path = "../datafusion" }
tokio = { version = "1.0", features = ["macros", "time"] }
test_helpers = { path = "../test_helpers" }

[features]
default = []
# Enable features for benchmarking
bench = ["mutable_buffer/nocache"]
