[package]
name = "sqlx-hotswap-pool"
authors = ["Marko Mikulicic <mkm@influxdata.com>"]
version = "0.0.0"
edition = "2021"
description = "Workaround for the lack of dyanmic credential update support in sqlx"

# Prevent this from being published to crates.io!
publish = false

[dependencies]
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "postgres", "json", "tls"] }
either = "1.6.1"
tokio = { version = "1.18", features = ["rt-multi-thread", "macros", "parking_lot"] }
futures = "0.3"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
dotenv = "0.15.0"
rand = { version = "0.8", features = ["small_rng"] }
