[package]
name = "mutable_batch"
description = "A mutable arrow RecordBatch"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
chrono = { version = "0.4", default-features = false }
data_types = { path = "../data_types" }
iox_time = { path = "../iox_time" }
schema = { path = "../schema" }
snafu = "0.7"
hashbrown = { workspace = true }
itertools = "0.10"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
mutable_batch_lp = { path = "../mutable_batch_lp" }
rand = "0.8"
