[package]
name = "mutable_batch"
version = "0.1.0"
edition = "2021"
description = "A mutable arrow RecordBatch"

[dependencies]
arrow = { version = "7.0", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
chrono = { version = "0.4", default-features = false }
data_types = { path = "../data_types" }
schema = { path = "../schema" }
snafu = "0.7"
hashbrown = "0.11"
itertools = "0.10"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
rand = "0.8"
