[package]
name = "ioxd_router2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
data_types2 = { path = "../data_types2" }
clap_blocks = { path = "../clap_blocks" }
generated_types = { path = "../generated_types" }
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
router2 = { path = "../router2" }
service_grpc_testing = { path = "../service_grpc_testing" }
time = { path = "../time" }
trace = { path = "../trace" }
trace_http = { path = "../trace_http" }
write_buffer = { path = "../write_buffer" }
write_summary = { path = "../write_summary" }

# Crates.io dependencies, in alphabetical order
arrow-flight = "11"
async-trait = "0.1"
hashbrown = "0.12"
hyper = "0.14"
thiserror = "1.0.30"
tokio = { version = "1.17", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7.1" }
tonic = "0.6"
tonic-health = "0.5.0"
tonic-reflection = "0.3.0"
workspace-hack = { path = "../workspace-hack"}
