[package]
name = "predicate"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { version = "7.0", features = ["prettyprint"] }
chrono = { version = "0.4", default-features = false }
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
schema = { path = "../schema" }
observability_deps = { path = "../observability_deps" }
ordered-float = "2"
regex = "1"
serde_json = "1.0.72"
snafu = "0.7"
sqlparser = "0.13.0"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
test_helpers = { path = "../test_helpers" }
tokio = { version = "1.13", features = ["macros", "parking_lot"] }
