[package]
name = "predicate"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
chrono = { version = "0.4", default-features = false }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
itertools = "0.11"
observability_deps = { path = "../observability_deps" }
query_functions = { path = "../query_functions"}
schema = { path = "../schema" }
snafu = "0.7"
sqlparser = "0.36.1"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
test_helpers = { path = "../test_helpers" }
