[package]
name = "predicate"
version = "0.1.0"
edition = "2018"

[dependencies]
arrow = { version = "5.5", features = ["prettyprint"] }
chrono = "0.4"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
generated_types = { path = "../generated_types" }
schema = { path = "../schema" }
observability_deps = { path = "../observability_deps" }
ordered-float = "2"
regex = "1"
serde_json = "1.0.67"
snafu = "0.6.9"
sqlparser = "0.12.0"

[dev-dependencies]
test_helpers = { path = "../test_helpers" }
tokio = { version = "1.11", features = ["macros"] }
