[package]
name = "predicate"
version = "0.1.0"
edition = "2018"

[dependencies]
arrow = { version = "5.0", features = ["prettyprint"] }
chrono = "0.4"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
generated_types = { path = "../generated_types" }
internal_types = { path = "../internal_types" }
observability_deps = { path = "../observability_deps" }
regex = "1"
snafu = "0.6.9"
sqlparser = "0.10.0"

[dev-dependencies]
tokio = { version = "1.11", features = ["macros"] }
