[package]
name = "ioxd_router"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies, in alphabetical order
data_types = { path = "../data_types" }
clap_blocks = { path = "../clap_blocks" }
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
object_store = "0.3.0"
observability_deps = { path = "../observability_deps" }
router = { path = "../router" }
sharder = { path = "../sharder" }
trace = { path = "../trace" }
write_buffer = { path = "../write_buffer" }
write_summary = { path = "../write_summary" }

# Crates.io dependencies, in alphabetical order
async-trait = "0.1"
hashbrown = "0.12"
hyper = "0.14"
thiserror = "1.0.32"
tokio = { version = "1.20", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = { version = "0.7.3" }
workspace-hack = { path = "../workspace-hack"}
