[package]
name = "test_helpers_end_to_end_ng"
version = "0.1.0"
edition = "2021"

[dependencies] # In alphabetical order
arrow = { version = "12", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
assert_cmd = "2.0.2"
bytes = "1.0"
futures = "0.3"
generated_types = { path = "../generated_types" }
http = "0.2.0"
hyper = "0.14"
influxdb_iox_client = { path = "../influxdb_iox_client", features = ["flight", "format", "write_lp"] }
nix = "0.24"
lazy_static = "1.4.0"
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.10.0", features = ["parking_lot"] }
parking_lot = "0.12"
prost = "0.10"
rand = "0.8.3"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls" , "postgres", "uuid" ] }
tempfile = "3.1.0"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
tokio = { version = "1.18", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = "0.7"
tonic = "0.7"
workspace-hack = { path = "../workspace-hack"}
