[package]
name = "delorean_parquet"
version = "0.1.0"
authors = ["Andrew Lamb <alamb@influxdata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.2"
log = "0.4.8"
parquet = "1.0.0"

delorean_table = { path = "../delorean_table" }
delorean_table_schema = { path = "../delorean_table_schema" }


[dev-dependencies]
delorean_test_helpers = { path = "../delorean_test_helpers" }
