[package]
name = "mutable_batch_tests"
version = "0.1.0"
edition = "2021"
description = "MutableBatch integration tests and benchmarks"

[dependencies]
dml = { path = "../dml" }
flate2 = "1.0"
generated_types = { path = "../generated_types" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
prost = "0.9"

[dev-dependencies]
bytes = "1.0"
criterion = "0.3"

[[bench]]
name = "write_lp"
harness = false


[[bench]]
name = "write_pb"
harness = false
