[package]
name = "mutable_batch_tests"
description = "MutableBatch integration tests and benchmarks"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dml = { path = "../dml" }
flate2 = "1.0"
generated_types = { path = "../generated_types" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
prost = "0.11"

[dev-dependencies]
bytes = "1.3"
criterion = { version = "0.4", default-features = false, features = ["rayon"]}
data_types = { path = "../data_types", default-features = false }

[[bench]]
name = "write_lp"
harness = false

[[bench]]
name = "write_pb"
harness = false


[lib]
# Allow --save-baseline to work
# https://github.com/bheisler/criterion.rs/issues/275
bench = false
