[package]
name = "storage"
version = "0.1.0"
authors = ["alamb <andrew@nerdnetworks.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.2"
async-trait = "0.1"
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.6.1"
tracing = "0.1"
croaring = "0.4.5"
chrono = "0.4"

arrow_deps = { path = "../arrow_deps" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
data_types = { path = "../data_types" }
test_helpers = { path = "../test_helpers" }
