[package]
name = "mutable_batch_pb"
version = "0.1.0"
edition = "2021"
description = "Conversion logic for binary write protocol <-> MutableBatch"

[dependencies]
arrow_util = { path = "../arrow_util" }
dml = { path = "../dml" }
generated_types = { path = "../generated_types" }
hashbrown = "0.11"
mutable_batch = { path = "../mutable_batch" }
schema = { path = "../schema" }
snafu = "0.7"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
mutable_batch_lp = { path = "../mutable_batch_lp" }
