[package]
name = "iox_time"
description = "Time functionality for IOx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono = { version = "0.4.23", default-features = false, features = ["clock", "std"] }
parking_lot = "0.12"
tokio = { version = "1.25", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
