[package]
name = "wal"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
byteorder = "1.3.4"
crc32fast = "1.2.0"
futures = "0.3.4"
itertools = "0.9.0"
once_cell = { version = "1.4.0", features = ["parking_lot"] }
regex = "1.3.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
snafu = "0.6.6"
snap = "1.0.0"
tokio = { version = "1.0", features=["macros", "fs"] }
tracing = "0.1"

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
