[package]
name = "wal"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
crc32fast = "1.2.0"
snafu = "0.6.6"
snap = "1.0.0"
regex = "1.3.7"
itertools = "0.9.0"
once_cell = "1.4.0"
futures = "0.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
tracing = "0.1"
tokio = { version = "0.2", features = ["full"] }


[dev-dependencies]
test_helpers = { path = "../test_helpers" }
