[package]
name = "trace_exporters"
description = "Additional tracing exporters for IOx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3"
iox_time = { path = "../iox_time" }
observability_deps = { path = "../observability_deps" }
snafu = "0.7"
thrift = { version = "0.17.0" }
tokio = { version = "1.25", features = ["macros", "parking_lot", "rt", "sync"] }
trace = { path = "../trace" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
