[package]
name = "query_tests"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "Tests of the query engine against different database configurations"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
once_cell = { version = "1.4.0", features = ["parking_lot"] }
predicate = { path = "../predicate" }
query = { path = "../query" }
server = { path = "../server" }

[dev-dependencies]
arrow = { version = "5.5", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
data_types = { path = "../data_types" }
internal_types = { path = "../internal_types" }
metric = { path = "../metric" }
object_store = { path = "../object_store" }
snafu = "0.6.3"
tempfile = "3.1.0"
test_helpers = { path = "../test_helpers" }
tokio = { version = "1.11", features = ["macros", "time"] }
