[package]
name = "query_tests"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"
description = "Tests of the query engine against different database configurations"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
db = { path = "../db" }
once_cell = { version = "1.4.0", features = ["parking_lot"] }
predicate = { path = "../predicate" }
query = { path = "../query" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
arrow = { version = "7.0", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
metric = { path = "../metric" }
object_store = { path = "../object_store" }
schema = { path = "../schema" }
snafu = "0.7"
tempfile = "3.1.0"
test_helpers = { path = "../test_helpers" }
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread", "time"] }
