[package]
name = "mutable_batch_lp"
description = "Conversion logic for line protocol -> MutableBatch"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hashbrown = { workspace = true }
influxdb-line-protocol = { path = "../influxdb_line_protocol" }
mutable_batch = { path = "../mutable_batch" }
snafu = "0.7"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
assert_matches = "1.5.0"
criterion = { version = "0.5", default-features = false, features = ["rayon"]}
schema = { path = "../schema" }

[[bench]]
name = "parse_lp"
harness = false


[lib]
# Allow --save-baseline to work
# https://github.com/bheisler/criterion.rs/issues/275
bench = false
