[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
pin-project = "1.0"
tokio = { version = "1.21" }
tokio-util = { version = "0.7.3" }
workspace-hack = { path = "../workspace-hack"}

# use libc on unix like platforms to set worker priority in DedicatedExecutor
[target."cfg(unix)".dependencies.libc]
version = "0.2"
