[package]
name = "influxdb_storage_client"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2018"

[dependencies]
client_util = { path = "../client_util" }
generated_types = { path = "../generated_types" }
prost = "0.8"
tonic = { version = "0.5.0" }
futures-util = { version = "0.3.1" }

[dev-dependencies]