[package]
name = "service_grpc_object_store"
version = "0.1.0"
edition = "2021"

[dependencies]
data_types = { path = "../data_types" }
futures = "0.3"
generated_types = { path = "../generated_types" }
iox_catalog = { path = "../iox_catalog" }
object_store = "0.4.0"
observability_deps = { path = "../observability_deps" }
parquet_file = { path = "../parquet_file" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = "0.8"
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
bytes = "1.2"
metric = { path = "../metric" }
