[package]
name = "router2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dml = { path = "../dml" }
generated_types = { path = "../generated_types" }
hyper = "0.14"
metric = { path = "../metric" }
thiserror = "1.0"
tonic = "0.6"
trace = { path = "../trace/" }
workspace-hack = { path = "../workspace-hack"}
