[package]
name = "arrow_util"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "Apache Arrow utilities"

[dependencies]

arrow = { version = "5.5", features = ["prettyprint"] }
ahash = "0.7.5"
num-traits = "0.2"
snafu = "0.6"
hashbrown = "0.11"
# used by arrow anyway (needed for printing workaround)
chrono = "0.4"
prettytable-rs = "0.8"

[dev-dependencies]
rand = "0.8.3"
