[package]
name = "arrow_util"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "Apache Arrow utilities"

[dependencies]

arrow = { path = "../arrow" }
ahash = "0.7.2"
num-traits = "0.2"
futures = "0.3"
snafu = "0.6"
hashbrown = "0.11"

[dev-dependencies]
rand = "0.8.3"
