[package]
name = "schema"
description = "IOx Schema definition"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
hashbrown = { workspace = true }
indexmap = { version = "1.9", features = ["std"] }
itertools = "0.10.5"
observability_deps = { path = "../observability_deps" }
snafu = "0.7"
workspace-hack = { path = "../workspace-hack"}
