[package]
name = "schema"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"
description = "IOx Schema definition"

[dependencies]
arrow = { version = "21.0.0", features = ["prettyprint"] }
hashbrown = "0.12"
indexmap = { version = "1.9", features = ["std"] }
itertools = "0.10.1"
observability_deps = { path = "../observability_deps" }
snafu = "0.7"
workspace-hack = { path = "../workspace-hack"}
