[package]
name = "generated_types"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2021"

[dependencies] # In alphabetical order
bytes = "1.0"
data_types = { path = "../data_types", optional = true }
data_types2 = { path = "../data_types2", optional = true }
datafusion = { path = "../datafusion", optional = true }
observability_deps = { path = "../observability_deps" }
pbjson = "0.3"
pbjson-types = "0.2"
predicate = { path = "../predicate", optional = true }
prost = "0.9"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
tonic = "0.6"
time = { path = "../time" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
data_types = { path = "../data_types" }
num_cpus = "1.13.0"

[build-dependencies] # In alphabetical order
tonic-build = "0.6"
prost-build = "0.9"
pbjson-build = "0.3"

[features]
default = ["data_types_conversions"]
data_types_conversions = ["data_types", "data_types2", "datafusion", "predicate"]
