[package]
name = "generated_types"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
bytes = "1.0"
data_types = { path = "../data_types" }
futures = "0.3"
google_types = { path = "../google_types" }
observability_deps = { path = "../observability_deps" }
pbjson = { path = "../pbjson" }
prost = "0.8"
regex = "1.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.28"
tonic = "0.5"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
num_cpus = "1.13.0"

[build-dependencies] # In alphabetical order
# Pin specific version of the tonic-build dependencies to match arrow
proc-macro2 = "=1.0.27"
tonic-build = "0.5"
prost-build = "0.8"
pbjson_build = { path = "../pbjson_build" }
