[package]
name = "influxdb_tsm"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2021"

[dependencies] # In alphabetical order
integer-encoding = "3.0.2"
snafu = "0.7"
snap = "1.0.0"
observability_deps = { path = "../observability_deps" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
flate2 = "1.0"
hex = "0.4.2"
rand = "0.8.3"
test_helpers = { path = "../test_helpers" }
