[package]
name = "service_common"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1.73"
bytes = "1.4"
datafusion = { workspace = true }
executor = { path = "../executor" }
iox_query = { path = "../iox_query" }
iox_query_influxql = { path = "../iox_query_influxql" }
iox_query_influxrpc = { path = "../iox_query_influxrpc" }
flightsql = { path = "../flightsql" }
metric = { path = "../metric" }
parking_lot = "0.12"
predicate = { path = "../predicate" }
tonic = { workspace = true }
trace = { path = "../trace" }
tracker = { path = "../tracker" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
