[package]
name = "iox_gitops_adapter"
version = "0.1.0"
authors = ["Luke Bond <luke.n.bond@gmail.com>"]
edition = "2021"

# Prevent this from being published to crates.io!
publish = false

[[bin]]
name = "iox_gitops_adapter"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
chrono = "0.4.15"
clap = { version = "3", features = ["derive", "env"] }
dotenv = "0.15"
futures = "0.3"
k8s-openapi = { version = "0.14", features = ["v1_19", "schemars"], default-features = false }
kube = { version = "0.70", default-features = false, features = ["client", "rustls-tls", "derive"] }
kube-derive = { version = "0.70", default-features = false } # only needed to opt out of schema
kube-runtime = "0.70"
prost = "0.9"
schemars = { version = "0.8.8", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt-multi-thread", "macros", "parking_lot"] }
tonic = "0.6"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
workspace-hack = { path = "../workspace-hack"}
trogging = { path = "../trogging", default-features = false, features = ["clap"] }

[build-dependencies]
glob = "0.3.0"
pbjson-build = "0.3"
tonic-build = "0.6"

[dev-dependencies]
assert_matches = "1.5"
parking_lot = { version = "0.11.1" }
