[package]
name = "tracker"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2018"
description = "Utilities for tracking resource utilisation within IOx"

[dependencies]

chrono = "0.4"
futures = "0.3"
hashbrown = "0.11"
lock_api = "0.4.4"
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.2"
pin-project = "1.0"
tokio = { version = "1.11", features = ["macros", "time"] }
tokio-util = { version = "0.6.3" }

[dev-dependencies]
# Need the multi-threaded executor for testing
tokio = { version = "1.11", features = ["macros", "time", "rt-multi-thread"] }
