[package]
name = "data_types"
description = "Shared data types"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
croaring = "0.7.0"
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
iox_time = { path = "../iox_time" }
observability_deps = { path = "../observability_deps" }
ordered-float = "3"
percent-encoding = "2.2.0"
schema = { path = "../schema" }
serde = { version = "1.0", features = ["derive"] }
snafu = "0.7"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "uuid"] }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
