[package]
name = "data_types"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow_deps = { path = "../arrow_deps" }
chrono = { version = "0.4", features = ["serde"] }
crc32fast = "1.2.0"
flatbuffers = "0.6" # TODO: Update to 0.8
generated_types = { path = "../generated_types" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
percent-encoding = "2.1.0"
serde = "1.0"
snafu = "0.6"
tracing = "0.1"
regex = "1.4"
serde_regex = "1.1"

[dev-dependencies] # In alphabetical order
criterion = "0.3"
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "benchmark"
harness = false
