[package]
name = "data_types"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
description = "InfluxDB IOx data_types, shared between IOx instances and IOx clients"
edition = "2018"
readme = "README.md"

[dependencies] # In alphabetical order
bytes = "1.0"
chrono = "0.4"
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
num_cpus = "1.13.0"
observability_deps = { path = "../observability_deps" }
percent-encoding = "2.1.0"
regex = "1.4"
snafu = "0.6"
time = { path = "../time" }
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
