[package]
name = "data_types"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
description = "InfluxDB IOx data_types, shared between IOx instances and IOx clients"
edition = "2021"
readme = "README.md"

[dependencies] # In alphabetical order
bytes = "1.0"
num_cpus = "1.13.0"
observability_deps = { path = "../observability_deps" }
ordered-float = "2"
percent-encoding = "2.1.0"
regex = "1"
siphasher = "0.3"
snafu = "0.7"
time = { path = "../time" }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
