[package]
name = "client_util"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
description = "Shared code for IOx clients"
edition = "2021"

[dependencies]
http = "0.2.3"
prost = "0.9"
thiserror = "1.0.30"
tonic = { version = "0.6" }
tower = "0.4"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread"] }
