[package]
name = "service_grpc_schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_types = { path = "../data_types" }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
tonic = "0.8"
iox_catalog = { path = "../iox_catalog" }
workspace-hack = { path = "../workspace-hack"}


[dev-dependencies]
metric = { path = "../metric" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
