name = "example"

[[agents]]
name = "foo"

[[agents.measurements]]
name = "cpu"
tag_pairs = [
    {key = "host", template = "host-{{agent.id}}"},
]

[[agents.measurements.fields]]
name = "usage_user"
f64_range = [0.0, 100.0]

[[bucket_writers]]
ratio = 1.0
agents = [{name = "foo", count = 3, sampling_interval = "10s"}]
