# Welcome to the InfluxDB configuration file.

# If hostname (on the OS) doesn't return a name that can be resolved by the other 
# systems in the cluster, you'll have to set the hostname to an IP or something 
# that can be resovled here.
# hostname = ""

[logging]
# logging level can be one of "debug", "info", "warn" or "error"
level  = "info"
file   = "/tmp/influxdb/test/2/influxdb.log"

# Configure the admin server
[admin]
port   = 60505
assets = "./admin"

# Configure the http api
[api]
port = 60506

# Raft configuration
[raft]
# The raft port should be open between all servers in a cluster.
# However, this port shouldn't be accessible from the internet.

port = 60507

# Where the raft logs are stored. The user running InfluxDB will need read/write access.
dir  = "/tmp/influxdb/test/2/raft"

[storage]
dir = "/tmp/influxdb/test/2/db"

[cluster]
# A comma separated list of servers to seed
# this server. this is only relevant when the
# server is joining a new cluster. Otherwise
# the server will use the list of known servers
# prior to shutting down. Any server can be pointed to
# as a seed. It will find the Raft leader automatically.

# Here's an example. Note that the port on the host is the same as the raft port.
seed-servers = ["localhost:60501"]

# Replication happens over a TCP connection with a Protobuf protocol.
# This port should be reachable between all servers in a cluster.
# However, this port shouldn't be accessible from the internet.

protobuf_port = 60508
