[package]
name = "query_functions"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
chrono = { version = "0.4", default-features = false }
datafusion = { workspace = true }
itertools = "0.10.5"
observability_deps = { path = "../observability_deps" }
once_cell = "1"
regex = "1"
regex-syntax = "0.6.28"
schema = { path = "../schema" }
snafu = "0.7"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
tokio = { version = "1.25", features = ["macros", "parking_lot"] }
datafusion_util = { path = "../datafusion_util" }
