[package]
name = "query_functions"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arrow = { workspace = true }
chrono = { version = "0.4", default-features = false }
datafusion = { workspace = true }
once_cell = "1"
regex = "1"
regex-syntax = "0.8.1"
schema = { path = "../schema" }
snafu = "0.8"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
datafusion_util = { path = "../datafusion_util" }
itertools = "0.12.0"
tokio = { version = "1.35", features = ["macros", "parking_lot"] }
