[package]
name = "influxdb_iox"
default-run = "influxdb_iox"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
arrow-flight = { workspace = true }
clap_blocks = { path = "../clap_blocks" }
compactor = { path = "../compactor" }
compactor2 = { path = "../compactor2" }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
generated_types = { path = "../generated_types" }
import = { path = "../import" }
influxdb_iox_client = { path = "../influxdb_iox_client", features = ["flight", "format"] }
influxdb_storage_client = { path = "../influxdb_storage_client" }
influxrpc_parser = { path = "../influxrpc_parser"}
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common"}
ioxd_compactor = { path = "../ioxd_compactor"}
ioxd_compactor2 = { path = "../ioxd_compactor2"}
ioxd_ingest_replica = { path = "../ioxd_ingest_replica" }
ioxd_ingester = { path = "../ioxd_ingester"}
ioxd_ingester2 = { path = "../ioxd_ingester2"}
ioxd_garbage_collector = { path = "../ioxd_garbage_collector" }
ioxd_querier = { path = "../ioxd_querier"}
ioxd_router = { path = "../ioxd_router"}
ioxd_test = { path = "../ioxd_test"}
metric = { path = "../metric" }
object_store = "0.5.4"
object_store_metrics = { path = "../object_store_metrics" }
observability_deps = { path = "../observability_deps" }
panic_logging = { path = "../panic_logging" }
parquet_file = { path = "../parquet_file" }
parquet_to_line_protocol = { path = "../parquet_to_line_protocol" }
prost = { version = "0.11" }
iox_query = { path = "../iox_query" }
schema = { path = "../schema" }
sharder = { path = "../sharder" }
iox_time = { path = "../iox_time" }
trace_exporters = { path = "../trace_exporters" }
trogging = { path = "../trogging", default-features = false, features = ["clap"] }

# Crates.io dependencies, in alphabetical order
nu-ansi-term = "0.46.0"
arrow = { workspace = true, features = ["prettyprint"] }
backtrace = "0.3"
bytes = "1.4"
clap = { version = "4", features = ["derive", "env"] }
comfy-table = { version = "6.1", default-features = false }
console-subscriber = { version = "0.1.8", optional = true, features = ["parking_lot"] }
dotenvy = "0.15.6"
futures = "0.3"
futures-util = { version = "0.3" }
flate2 = "1.0"
hashbrown = { workspace = true }
http = "0.2.9"
humantime = "2.1.0"
itertools = "0.10.5"
libc = { version = "0.2" }
num_cpus = "1.15.0"
once_cell = { version = "1.17", features = ["parking_lot"] }
rustyline = { version = "10.1", default-features = false }
serde_json = "1.0.93"
snafu = "0.7"
tempfile = "3.1.0"
thiserror = "1.0.38"
tikv-jemalloc-ctl = { version = "0.5.0", optional = true }
tokio = { version = "1.25", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time", "io-std"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7.7", features = ["compat"] }
tonic = "0.8"
uuid = { version = "1", features = ["v4"] }
# jemalloc-sys with unprefixed_malloc_on_supported_platforms feature and heappy are mutually exclusive
tikv-jemalloc-sys = { version = "0.5.3", optional = true, features = ["unprefixed_malloc_on_supported_platforms"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
# In alphabetical order
arrow_util = { path = "../arrow_util" }
assert_cmd = "2.0.8"
async-trait = "0.1"
predicate = { path = "../predicate" }
predicates = "2.1.0"
serde = "1.0.152"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
test_helpers_end_to_end = { path = "../test_helpers_end_to_end" }

[features]
default = ["jemalloc_replacing_malloc"]

azure = ["clap_blocks/azure", "import/azure"] # Optional Azure Object store support
gcp = ["clap_blocks/gcp", "import/gcp"] # Optional GCP object store support
aws = ["clap_blocks/aws", "import/aws"] # Optional AWS / S3 object store support
pprof = ["ioxd_common/pprof"] # Optional http://localhost:8080/debug/pprof/profile support
heappy = ["ioxd_common/heappy"] # Optional http://localhost:8080/debug/pproc/alloc support

# Enable tokio_console support (https://github.com/tokio-rs/console)
#
# Requires enabling trace level tracing events for [tokio,runtime].
tokio_console = ["console-subscriber", "tokio/tracing", "observability_deps/release_max_level_trace"]

# heappy is an optional feature; Not on by default as it
# runtime overhead on all allocations (calls to malloc).
# Cargo cannot currently implement mutually exclusive features so let's force every build
# to pick either heappy or jemalloc_replacing_malloc feature at least until we figure out something better.
jemalloc_replacing_malloc = ["tikv-jemalloc-sys", "tikv-jemalloc-ctl"]

# Implicit feature selected when running under `clippy --all-features` to accept mutable exclusive features during
# linting
clippy = []
