[package]
name = "iox_catalog"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1.64"
data_types = { path = "../data_types" }
futures = "0.3"
iox_time = { version = "0.1.0", path = "../iox_time" }
log = "0.4"
metric = { version = "0.1.0", path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
observability_deps = { path = "../observability_deps" }
snafu = "0.7"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls" , "postgres", "uuid" ] }
sqlx-hotswap-pool = { path = "../sqlx-hotswap-pool" }
thiserror = "1.0.38"
tokio = { version = "1.25", features = ["io-util", "macros", "parking_lot", "rt-multi-thread", "time"] }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
assert_matches = "1.5.0"
dotenvy = "0.15.6"
mutable_batch_lp = { path = "../mutable_batch_lp" }
paste = "1.0.11"
pretty_assertions = "1.3.0"
rand = "0.8"
tempfile = "3"
test_helpers = { path = "../test_helpers" }
