[write]
  concurrency = 10
  batch_size = 5000
  batch_interval = "0s"
  database = "stress"
  precision = "n"
  address = "localhost:8086"
  reset_database = true
  # doesnt do anything
  starting_point = 0 # how far back in time to go in weeks

[[series]]
  point_count = 10 # number of points that will be written for each of the series
  measurement = "cpu"
  series_count = 100000

 # tag_count = 20 # number of "generic" tags on a series (e.g. tag-key-1=tag-value, ... ,tag-key-20=tag-value)

  [[series.tag]]
    key = "host"
    value = "idk"

  [[series.tag]]
    key = "location"
    value = "lame"

  [[series.field]]
    key = "value"
    type = "float64"

