[package]
name = "grpc-router-test-gen"
version = "0.1.0"
authors = ["Marko Mikulicic <mkm@influxdata.com>"]
edition = "2021"
description = "Protobuf used in test for the grpc-router crate; need to be in a separate create because of linter limitations"

[dependencies]
tonic = "0.7"
prost = "0.10"

[build-dependencies]
tonic-build = "0.7"
prost-build = "0.10"
