[package]
name = "influxdb3_telemetry"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures-util.workspace = true
futures.workspace = true
num.workspace = true
observability_deps.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
test-log.workspace = true
proptest.workspace = true
mockito.workspace = true
mockall.workspace = true

