[package]
name = "trace_http"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2018"
description = "Distributed tracing support for HTTP services"

[dependencies]

trace = { path = "../trace" }
futures = "0.3"
http = "0.2"
http-body = "0.4"
itertools = "0.10"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11"
pin-project = "1.0"
snafu = "0.6"
tower = "0.4"

[dev-dependencies]
