[package]
name = "trace_http"
description = "Distributed tracing support for HTTP services"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bytes = "1.5"
trace = { path = "../trace" }
futures = "0.3"
hashbrown = { workspace = true }
http = "0.2"
http-body = "0.4"
itertools = "0.12"
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
pin-project = "1.1"
snafu = "0.8"
tower = "0.4"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
