[package]
name = "partition"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arrow = { workspace = true }
chrono = { version = "0.4", default-features = false }
data_types = { path = "../data_types" }
hashbrown = { workspace = true }
mutable_batch = { path = "../mutable_batch" }
percent-encoding = "2.3.1"
schema = { path = "../schema" }
thiserror = "1.0.56"
unicode-segmentation = "1.10.1"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.5", default-features = false, features = [
    "rayon",
] }
generated_types = { path = "../generated_types" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
paste = "1.0.14"
proptest = { version = "1.4.0", default-features = false }
rand = "0.8"
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "partitioner"
harness = false
