[package]
name = "service_grpc_flight"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
authz = { path = "../authz" }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
flightsql = { path = "../flightsql" }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
iox_query = { path = "../iox_query" }
iox_query_influxql = { path = "../iox_query_influxql" }
iox_query_params = { path = "../iox_query_params" }
service_common = { path = "../service_common" }
tower_trailer = { path = "../tower_trailer"}
trace = { path = "../trace"}
trace_http = { path = "../trace_http"}
tracker = { path = "../tracker" }

# Crates.io dependencies, in alphabetical order
arrow = { workspace = true }
arrow-flight = { workspace = true }
bytes = "1.5"
futures = "0.3"
prost = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.111"
snafu = "0.8"
tokio = { version = "1.35", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tonic = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
async-trait = "0.1"
metric = { path = "../metric" }
test_helpers = { path = "../test_helpers" }
