[package]
name = "service_grpc_flight"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
authz = { path = "../authz" }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
flightsql = { path = "../flightsql" }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
iox_query = { path = "../iox_query" }
service_common = { path = "../service_common" }
trace = { path = "../trace"}
trace_http = { path = "../trace_http"}
tracker = { path = "../tracker" }

# Crates.io dependencies, in alphabetical order
arrow = { workspace = true, features = ["prettyprint"] }
arrow-flight = { workspace = true, features=["flight-sql-experimental"] }
bytes = "1.5"
futures = "0.3"
prost = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.106"
snafu = "0.7"
tokio = { version = "1.32", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tonic = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
async-trait = "0.1"
metric = { path = "../metric" }
test_helpers = { path = "../test_helpers" }
