[package]
name = "metrics"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2018"

# This crate contains the application-specific abstraction of the metrics
# implementation for IOx. Any crate that wants to expose telemetry should use
# this crate.
#
# The crate exposes a special type of metrics registry which allows users to
# isolate their metrics from the rest of the system so they can be tested
# in isolation.


[dependencies] # In alphabetical order
dashmap = { version = "4.0.1" }
hashbrown = "0.11"
observability_deps = { path = "../observability_deps" }
opentelemetry = "0.16"
opentelemetry-prometheus = "0.9"
parking_lot = "0.11.1"
prometheus = "0.12"
snafu = "0.6"

[dev-dependencies] # In alphabetical order
